ALTER TABLE today_skin
    DROP CONSTRAINT IF EXISTS chk_diet_type;

ALTER TABLE today_skin
    ADD CONSTRAINT chk_diet_type CHECK (
        diet_type IS NULL OR diet_type ~
        '^(DAIRY|FRUIT|SPICY_FOOD|CAFFEINE|HIGH_FAT|SUGAR|SODA|ALCOHOL)(,(DAIRY|FRUIT|SPICY_FOOD|CAFFEINE|HIGH_FAT|SUGAR|SODA|ALCOHOL))*$'
        );

ALTER TABLE today_skin
    DROP CONSTRAINT IF EXISTS chk_skin_status;